export const REQUEST_MOVIES_START = 'REQUEST_MOVIES_START';
export const REQUEST_MOVIES_ERROR = 'REQUEST_MOVIES_ERROR';
export const RECORD_MOVIES_DATA_TO_STORE = 'RECORD_MOVIES_DATA_TO_STORE';
export const SAVE_FILTER_VALUE = 'SAVE_FILTER_VALUE';
export const SAVE_SORT_VALUE = 'SAVE_SORT_VALUE';
export const TOGGLE_SORT_ARROW = 'TOGGLE_SORT_ARROW';
