export const REQUEST_MOVIES_START = "REQUEST_MOVIES_START";
export const REQUEST_MOVIES_ERROR = "REQUEST_MOVIES_ERROR";
export const RECORD_MOVIES_DATA_TO_STORE = "RECORD_MOVIES_DATA_TO_STORE";
export const SAVE_FILTER_VALUE = "SAVE_FILTER_VALUE";
export const SAVE_SORT_VALUE = "SAVE_SORT_VALUE";
export const TOGGLE_SORT_ARROW = "TOGGLE_SORT_ARROW";
export const RESET_MAIN_PAGE_STATE = "RESET_MAIN_PAGE_STATE";
export const SAVE_SELECTED_MOVIE = "SAVE_SELECTED_MOVIE";

//Movie form
export const SET_FORM_TITLE = "SET_FORM_TITLE";
export const SET_FORM_DATE = "SET_FORM_DATE";
export const SET_FORM_URL = "SET_FORM_URL";
export const SET_FORM_GENRES = "SET_FORM_GENRES";
export const SET_FORM_OVERVIEW = "SET_FORM_OVERVIEW";
export const SET_FORM_RUNTIME = "SET_FORM_RUNTIME";
export const RESET_MOVIE_FORM = "RESET_MOVIE_FORM";
