export const REQUEST_MOVIE_START = "REQUEST_MOVIE_START";
export const REQUEST_MOVIE_ERROR = "REQUEST_MOVIE_ERROR";
export const RECORD_MOVIE_DATA_TO_STORE = "RECORD_MOVIE_DATA_TO_STORE";
export const RESET_MOVIE_DETAILS_PAGE_STATE = "RESET_MOVIE_DETAILS_PAGE_STATE";
